# See https://github.com/rubocop-hq/rubocop/blob/master/manual/configuration.md

AllCops:
  Exclude:
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - '.git/**/*'
    - 'config/**/*'
    - 'bin/**/*'
    - 'config.ru'
    - 'db/schema'
Style/Documentation:
  Enabled: false
Metrics/BlockLength:
  Enabled: true
  Max: 25
  ExcludedMethods:
    - refine
  Exclude:
    - '**/*.gemspec'
    - 'spec/*_spec.rb'
Metrics/MethodLength:
  Enabled: true
  Max: 15
  ExcludedMethods: []
Metrics/LineLength:
  Enabled: true
  Max: 120
Style/NegatedIf:
  Enabled: false